[package]
name = "aardvark-dns"
version = "1.5.0"
edition = "2018"
authors = ["github.com/containers"]
license = "Apache-2.0"
readme = "README.md"
description = "A container-focused DNS server"
homepage = "https://github.com/containers/aardvark-dns"
repository = "https://github.com/containers/aardvark-dns"
categories = ["containers", "networking", "dns", "podman"]
exclude = ["/.cirrus.yml", "/.github/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.23", features = ["derive"] }
syslog = "^6.0"
log = "0.4.17"
trust-dns-server = "0.22.0"
trust-dns-proto = "0.22.0"
trust-dns-client = "0.22.0"
anyhow = "1.0.68"
futures-util = { version = "0.3.25", default-features = false }
signal-hook = "0.3.13"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread", "net"] }
async-broadcast = "0.5.0"
resolv-conf = "0.7.0"
nix = "0.26.2"
libc = "0.2"

[build-dependencies]
chrono = "*"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
